# Generated by Django 4.2.3 on 2023-09-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='order_total',
            field=models.FloatField(null=True),
        ),
    ]
