# Generated by Django 4.2.3 on 2023-09-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_delivery_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='tax',
            field=models.FloatField(null=True),
        ),
    ]
