# Generated by Django 4.2.3 on 2023-09-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_delivery_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('credit', 'credit'), ('cash', 'cash'), ('paypal', 'paypal')], max_length=20)),
            ],
        ),
    ]
