# Generated by Django 4.2.3 on 2023-09-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address_line_1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='address_line_2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='profileImage'),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
