# Generated by Django 4.2.3 on 2023-08-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_cat',
            field=models.CharField(choices=[('Size', 'Size'), ('color', 'color')], max_length=6),
        ),
    ]
