# Generated by Django 4.2.3 on 2023-08-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_variation'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_variation',
            field=models.ManyToManyField(blank=True, related_name='product_variation', to='main.variation'),
        ),
    ]
